### ISSUE TITLE
Interface broken

### ISSUE THREAD

**Issue by BoubakAy** [kkga/spacegray#187] opened 2016-11-28 15:35 UTC
Since last update, when any Spacegray theme is activated, the interface is buggy, some elements does not show up, etc...
(see attached)
![capture d ecran 2016-11-28 a 16 34 44](https://cloud.githubusercontent.com/assets/10706063/20674290/a61559a6-b588-11e6-9d0b-5b84d1559445.jpg)

**Comment by marcofugaro** [comment] 2016-11-28 15:40
did you try restarting your sublime? if not please share your sublime version

**Comment by BoubakAy** [comment] 2016-11-28 15:43
Yep I restarted it several times. It’s 2.0.2 version.
I also tried to install the previous version of your package, and it worked just fine.

**Comment by marcofugaro** [comment] 2016-11-28 16:38
your problem is at line `"characters": "\",`

the symbol `\` means escaping, so your closing `"` was ignored.

Here is the fixed line `"characters": "\\",`
Test it and the problem shouldn't occur again.

Closing as it's not related to spacegray.

**Comment by BoubakAy** [comment] 2016-11-28 17:26
Oh this was only a copy-paste error probably.

Even if it's right, still there is the issue... it happens only with this theme, as soon as i switch to default one, it's ok...

**Comment by marcofugaro** [comment] 2016-11-28 18:41
Ok then it's an issue with sublime 2.

For now try doing the [manual installation](https://github.com/kkga/spacegray/blob/master/README.md#manual) of the release 1.2.0, also by removing the new version from the package manager

**Comment by BoubakAy** [comment] 2016-11-28 18:48
Thanks. I confirm that all works fine with 1.2.0. When I replace 'only' the sublime-theme file of 1.2.0 by the one from the last release, this produces graphical issues.

**Comment by typeoneerror** [comment] 2016-11-28 23:19
Similar issues. Tried with 1.2.0 manual install. Definitely looks like an ST2 issue.

<img width="828" alt="screen shot 2016-11-28 at 3 18 28 pm" src="https://cloud.githubusercontent.com/assets/218700/20690185/fbdcd45a-b57d-11e6-8a97-32d06600541b.png">

**Comment by typeoneerror** [comment] 2016-11-28 23:21
Confirmed: manual install of 1.2 works.

**Comment by ash106** [comment] 2016-11-29 09:39
I was having the same problem but I fixed it with #191.

**Comment by marcofugaro** [comment] 2016-11-29 10:26
@ash106 thanks for your help, new release should be rolling out https://github.com/kkga/spacegray/releases/tag/1.3.1

**Comment by BoubakAy** [comment] 2016-11-29 16:32
Confirmed : these issues disappeared ça thanks :) 
But now, file icons don't display, despite I set the parameter to true in ST settings file... am I the only one on ST2 to experience that problem?

**Comment by ash106** [comment] 2016-11-30 09:05
Sidebar icons don't work for me ins ST2 either, but I believe that's because they weren't added until ST3. I can't find any mention of them before ST3. Maybe it's worth adding a disclaimer to the readme? Something like `(only works in Sublime Text 3)`.

**Comment by marcofugaro** [comment] 2016-11-30 10:41
Yeah you're right @ash106, also the fileicons should be disabled by default, do you confirm that guys?

**Comment by BoubakAy** [comment] 2016-11-30 13:38
Oh ok... too bad. I agree, should be turned to off by default.

**Comment by marcofugaro** [comment] 2016-11-30 15:10
@BoubakAy you're saying you're still seeing the red squares in ST2 if you don't have `spacegray_fileicons: true,` in your settings?

**Comment by ash106** [comment] 2016-11-30 22:20
Mine looks fine by default
<img width="178" alt="screen shot 2016-11-30 at 4 16 00 pm" src="https://cloud.githubusercontent.com/assets/3224433/20773668/89736dce-b718-11e6-9896-bdcf712e60cb.png">

and then when I add `"spacegray_fileicons": true`, it just looks like this
<img width="183" alt="screen shot 2016-11-30 at 4 16 19 pm" src="https://cloud.githubusercontent.com/assets/3224433/20773691/a9deec00-b718-11e6-9995-389fb9df9830.png">

I don't ever have the red squares show up.

**Comment by BoubakAy** [comment] 2016-12-01 07:07
@marcofugaro No, red squares are definitely gone. No I just experience the same thing as @ash106, but if it's because ST2 does not support, that's fine ;)

**Comment by marcofugaro** [comment] 2016-12-01 10:04
Nice, closing

**Closed by marcofugaro** 2016-12-01 10:04 UTC
