### ISSUE TITLE
Add icon for folders that Sublime thinks are links

### ISSUE THREAD

**Issue by appsforartists** [kkga/spacegray#208] opened 2018-01-09 01:06 UTC
Some folders appear as if they have no contents - both open and closed, no files are listed beneath them.  Adding `"Theme - Spacegray"` to my `ignored_packages` fixes this.  Sublime r3156 on macOS 10.12.6.

**Comment by marcofugaro** [comment] 2018-01-09 08:05
Can't reproduce the bug, do you have an example repo where it happens or some screenshots?

**Comment by appsforartists** [comment] 2018-01-11 22:49
I think this was a coincidence - the root cause appears to be that some of my tools were making symlinks from `node_modules` to other `packages` in my project.  `n` comes before `p` lexicographically, so Sublime was treating `node_modules` as canonical and `packages` as dupes.

Spacegrey was masking the issue by not showing the link icon for the elided folders, but I think it was just coincidence that disabling it brought the contents back when I opened this issue.

**Comment by marcofugaro** [comment] 2018-01-14 16:38
There already is an icon for symlinks, it's a folder in an arrow in it, here is the relative code: https://github.com/kkga/spacegray/blob/9cddef9b5949100c84e87bc40e41885f4156b4de/Spacegray.sublime-theme#L699-L702

Tested it and it works fine, otherwise I don't know which files you are referring to, closing.

**Closed by marcofugaro** 2018-01-14 16:38 UTC
