### ISSUE TITLE
Syntax highlighting - as of Build 3103 (Feb 9, 2016) 

### ISSUE THREAD

**Issue by departure** [kkga/spacegray#181] opened 2016-02-09 19:14 UTC
As of Build 3103 (Feb 9, 2016) Javascript syntax highlighting is no longer working properly. It may be related to scope.

**Comment by RegisBiron** [comment] 2016-02-09 20:20
I can confirm that the Javascript syntax highlighting is not working properly with Build 3103.

**Comment by kkga** [comment] 2016-02-10 08:01
Hey guys, I'm not actively maintaining this repo for quite a while already. For the latest syntax themes you should go to their respective base16 repo: https://github.com/chriskempson/base16

**Comment by marcofugaro** [comment] 2016-02-10 17:44
@kkga It seems this repo doesn't have any active mantainers, I've made a PR about fileicons and it hasn't even been considered, I could help if you want.

**Comment by kkga** [comment] 2016-02-10 19:00
@marcofugaro yeah, if you want to keep the theme up to date that would be great!

**Comment by marcofugaro** [comment] 2016-02-10 23:10
Will do!

**Comment by kkga** [comment] 2016-02-10 23:11
Awesome! Added you as an administrator. Thanks!

> On Feb 11 2016, at 2:10 am, Marco &lt;notifications@github.com&gt; wrote:  

>

> Will do!

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/kkga/sp
acegray/issues/181#issuecomment-182630103).![](https://github.com/notification
s/beacon/ABZHmhJGypjTbbRifjivlmqWqlYlPqkcks5pi7rqgaJpZM4HWrhy.gif)

**Comment by mhkeller** [comment] 2016-02-11 20:40
Related discussion on javascript syntax highlighting in 3103 https://github.com/sublimehq/Packages/issues/141

**Comment by samholmes** [comment] 2016-02-11 21:56
In summary, what happened after updating to 3103; what made the theme break?

**Comment by marcofugaro** [comment] 2016-02-11 22:29
There's a new [syntax highlighting](https://www.sublimetext.com/docs/3/syntax.html), will look into this issue, thanks for the link @mhkeller

**Comment by mhkeller** [comment] 2016-02-11 23:09
As a short term fix, if you have another computer that hasn't upgraded yet, on OS X you can "Show Package Contents" and in the Mac OS folder (IIRC) you can copy the JavaScript package file. Copy it to your other computer, name it something different and now you should have a new syntax available to you that will look like the old version.

**Comment by marcofugaro** [comment] 2016-02-21 10:30
Yes [here](https://forum.sublimetext.com/t/javascript-syntax-highlighting-changes-in-3103/17328/33) is the fix, also looks like this is already fixed in the lastest devbuild.

New selectors were added, like the `variable.language.this.js` for the `this` in javascript, or [new $ cases](https://github.com/sublimehq/Packages/pull/96#issuecomment-183168552), which I will implement in the base16 color scheme if needed, but I need a reference about how base16 should look in the different cases of JS code, or do I compare it with default monokai?

**Comment by marcofugaro** [comment] 2016-02-27 13:29
This is how it looks with the new fixed `JavaScript.sublime-syntax`, how should it look?

![Screenshot](http://i.imgur.com/XNJh110.png)

**Comment by SamPotts** [comment] 2016-03-02 11:58
LESS highlighting is now also b0rked in the latest builds. Would be nice if Sublime and Atom somehow merged. We'd have the best of both worlds.

**Comment by marcofugaro** [comment] 2016-03-02 13:29
@samholmes Please report what's wrong on the sublime forums, people are working on fixing those issues, there are tons of threads about syntax highlighting

https://forum.sublimetext.com/

**Comment by SamPotts** [comment] 2016-03-02 22:03
Sorry, with the LESS I realised it wasn't actually auto-selecting the LESS syntax highlighting based on extension (for whatever reason), I had to re-set the option "Open all with current extension as" to use LESS.

**Comment by mhkeller** [comment] 2016-03-02 22:27
@marcofugaro per your question on how it should look, here's a quick side-by-side of how it used to be versus what I see now on the same code snippet. One caveat, I'm using [a fork](https://github.com/mhkeller/spacegray/commit/4f41f9bcafae6bd6f82c0570b14c23e1dd2cdbe2) that colors operators like `+` and `=` light purple. Everything else is the same as the original. 

Some thoughts for discussion:

1. I imagine not that many people would strongly object to putting Spacegray back to the pre-3103 colors.
2. The new syntax does give some handy changes that could be integrated into the Spacegray aesthetic. For example, `nextTick` is light blue in the new syntax and that seems more consistent. You could take a crack at updating this project with some new styles that are more consistent with what it was before. These red variables everywhere, for example, I find inconsistent with previous versions. In order to keep users happy who just want to keep pre-3103 style, you could make that available on a branch. Or keep this repo as pre-3103 style and make a new project called `Spacegray-Next` or something better.

#### Old style

<img width="657" alt="old-style" src="https://cloud.githubusercontent.com/assets/498744/13477415/392460da-e09a-11e5-8684-8e9d1100e9ea.png">

#### Build 3107 

<img width="657" alt="new-style" src="https://cloud.githubusercontent.com/assets/498744/13477414/391dd2ce-e09a-11e5-9639-099a1acc4281.png">

**Comment by SamPotts** [comment] 2016-03-02 22:30
I have to agree the new JS highlighting is a bit red heavy. Atom handles it well I think:

![screen shot 2016-03-03 at 9 29 35 am](https://cloud.githubusercontent.com/assets/719092/13477882/858efd80-e122-11e5-8a6c-abad46c42707.png)

**Comment by rtsao** [comment] 2016-03-09 19:11
FWIW I've had success with the Spacegray port here: https://github.com/saadq/Materialize

**Comment by oivva** [comment] 2016-03-16 07:41
You can try to add my color scheme builder into this theme or modify it to fit your needs. 
**Base16 Oceanic** preset is included (I just modified it a little bit). It has more prettier syntax highlighting and, yes, JS highlighting isn't so red centric. 
***
You can find it in this theme: [Otto](https://github.com/oivva/otto)

**Comment by jaredatch** [comment] 2016-05-15 14:49
Tried the Materialize Spacegray port but it has issues too.

I just want my (working) Spacegray back 😢

**Comment by ganni** [comment] 2016-05-15 14:56
Me tooo! I want my old spacegray back.

**Comment by saadq** [comment] 2016-05-23 04:28
Hey @jaredatch, I'm the creator of Materialize. I'm still actively developing my themes, so I would be happy to improve any syntax highlighting issues you guys seem to have with Material Spacegray. What improvements would you like to see?

**Comment by mhkeller** [comment] 2016-05-23 04:40
@saadq I'm all for any efforts to improve syntax highlighting but this specific exchange would be more appropriate as an issue on the materialize repo. 

All: if no one else has started, I'm going to try and take a crack at bringing the old style back to life next weekend. I'll make a new branch on my fork called 'pre-update'. Contributions welcome! If someone has already done some of the work, I'd happily contribute to what you already have.

**Comment by saadq** [comment] 2016-05-23 05:05
Feel free to use Material Spacegray as a base if you'd like, or I'd be happy to help out with any syntax highlighting adjustments if I can!

**Comment by marcofugaro** [comment] 2016-06-01 16:30
Sorry guys, I haven't had much free time for this recently, but will surely get on it this weekend. 
@saadq thanks for the help! will checkout how you solved things over at your theme and ask help if I need it.

@mhkeller sure any help is welcome,  will need to discuss with you about the old vs new JS highlighting.

Also I implemented fileicons here, but I need some testing before i can pull it in, especially on Mac OS. I have the pull request here currently open.

**Comment by brachycera** [comment] 2016-09-23 14:02
After updating to **Sublime 3124**, my Spacegray code highlighting (base16-ocean.dark) went all red like @mhkeller screenshot shows. My solution was to add the following lines to my base16-ocean.dark file.
```
<dict>
    <key>name</key>
    <string>Function call</string>
    <key>scope</key>
    <string>variable.function</string>
    <key>settings</key>
    <dict>
        <key>fontStyle</key>
        <string />
        <key>foreground</key>
        <string>#eff1f5</string>
    </dict>
</dict>
```
You can use https://github.com/bobef/ColorSchemeEditor to quickly edit the base16-ocean.dark.tmTheme. Since I use SublimeLinter my File was under `/Packages/User/SublimeLinter/base16-ocean.dark (SL).tmTheme`. (See this Link how [SublimeLinter manages Color Schemes](http://www.sublimelinter.com/en/latest/usage.html?highlight=color%20scheme#choosing-color-schemes))

![PHP](https://cloud.githubusercontent.com/assets/2804515/18788361/d3edc838-81a6-11e6-80dc-2cbf3e0acc6b.png)

![Javascript](https://cloud.githubusercontent.com/assets/2804515/18788392/f75e5af8-81a6-11e6-8e41-626893e7a43f.png)

**Comment by marcofugaro** [comment] 2016-11-20 17:01
Thank you @brachycera that solved the issue, made the function calls blue like the atom ocean16-dark package does. the PR is #186

**Comment by mhkeller** [comment] 2016-12-28 22:01
@brachycera very cool! I didn't know that tool existed. I've been hung up on trying to get some ruby-based theme editor to work so this is much easier. Setting the variable color back to pre-3103 so `#d3d0c8` seems like the most compatible change to make with this PR. That being said, I'm probably going to keep using my fork since I have a couple new things I want to add. Thanks for taking this over @marcofugaro!

**Comment by marcofugaro** [comment] 2016-12-28 22:45
Okay, closing, changes will be online in next patch release!

**Closed by marcofugaro** 2016-12-28 22:45 UTC
